#include <iostream>
#include <sstream>
#include <ac_datatype_plus>
#include <range.hpp>
#include <Eigen/Core>

using namespace std;

#define PACK(...) __VA_ARGS__

#define TEST_DEFINE_AND_SET(TYPE,VALUE)\
    {\
        TYPE t = { VALUE };\
        cout << "define " # TYPE " and set to " << VALUE << " and got " << t << endl;\
    }

#define TEST_DEFINE_AND_SET_COMPLEX(TYPE,VALUE)\
    {\
        ac_datatype::ac_complex<PACK(TYPE)> t = { VALUE };\
        cout << "define " # TYPE " and set to " << VALUE << " and got " << t << endl;\
    }


void test_defines()
{
	TEST_DEFINE_AND_SET(ac_datatype::int1, 1);
	TEST_DEFINE_AND_SET(ac_datatype::uint1, 1);
	TEST_DEFINE_AND_SET(ac_datatype::int2, 1);
	TEST_DEFINE_AND_SET(ac_datatype::uint2, 1);
	TEST_DEFINE_AND_SET(ac_datatype::int3, 1);
	TEST_DEFINE_AND_SET(ac_datatype::uint3, 1);
	TEST_DEFINE_AND_SET(ac_datatype::int4, 1);
	TEST_DEFINE_AND_SET(ac_datatype::uint4, 1);
	TEST_DEFINE_AND_SET(ac_datatype::int5, 1);
	TEST_DEFINE_AND_SET(ac_datatype::uint5, 1);
	TEST_DEFINE_AND_SET(ac_datatype::int6, 1);
	TEST_DEFINE_AND_SET(ac_datatype::uint6, 1);
	TEST_DEFINE_AND_SET(ac_datatype::int7, 1);
	TEST_DEFINE_AND_SET(ac_datatype::uint7, 1);
	TEST_DEFINE_AND_SET(ac_datatype::int8, 1);
	TEST_DEFINE_AND_SET(ac_datatype::uint8, 1);
	TEST_DEFINE_AND_SET(ac_datatype::int9, 1);
	TEST_DEFINE_AND_SET(ac_datatype::uint9, 1);
	TEST_DEFINE_AND_SET(ac_datatype::int10, 1);
	TEST_DEFINE_AND_SET(ac_datatype::uint10, 1);
	TEST_DEFINE_AND_SET(ac_datatype::int11, 1);
	TEST_DEFINE_AND_SET(ac_datatype::uint11, 1);
	TEST_DEFINE_AND_SET(ac_datatype::int12, 1);
	TEST_DEFINE_AND_SET(ac_datatype::uint12, 1);
	TEST_DEFINE_AND_SET(ac_datatype::int13, 1);
	TEST_DEFINE_AND_SET(ac_datatype::uint13, 1);
	TEST_DEFINE_AND_SET(ac_datatype::int14, 1);
	TEST_DEFINE_AND_SET(ac_datatype::uint14, 1);
	TEST_DEFINE_AND_SET(ac_datatype::int15, 1);
	TEST_DEFINE_AND_SET(ac_datatype::uint15, 1);
	TEST_DEFINE_AND_SET(ac_datatype::int16, 1);
	TEST_DEFINE_AND_SET(ac_datatype::uint16, 1);
	TEST_DEFINE_AND_SET(ac_datatype::int17, 1);
	TEST_DEFINE_AND_SET(ac_datatype::uint17, 1);
	TEST_DEFINE_AND_SET(ac_datatype::int18, 1);
	TEST_DEFINE_AND_SET(ac_datatype::uint18, 1);
	TEST_DEFINE_AND_SET(ac_datatype::int19, 1);
	TEST_DEFINE_AND_SET(ac_datatype::uint19, 1);
	TEST_DEFINE_AND_SET(ac_datatype::int20, 1);
	TEST_DEFINE_AND_SET(ac_datatype::uint20, 1);
	TEST_DEFINE_AND_SET(ac_datatype::int21, 1);
	TEST_DEFINE_AND_SET(ac_datatype::uint21, 1);
	TEST_DEFINE_AND_SET(ac_datatype::int22, 1);
	TEST_DEFINE_AND_SET(ac_datatype::uint22, 1);
	TEST_DEFINE_AND_SET(ac_datatype::int23, 1);
	TEST_DEFINE_AND_SET(ac_datatype::uint23, 1);
	TEST_DEFINE_AND_SET(ac_datatype::int24, 1);
	TEST_DEFINE_AND_SET(ac_datatype::uint24, 1);
	TEST_DEFINE_AND_SET(ac_datatype::int25, 1);
	TEST_DEFINE_AND_SET(ac_datatype::uint25, 1);
	TEST_DEFINE_AND_SET(ac_datatype::int26, 1);
	TEST_DEFINE_AND_SET(ac_datatype::uint26, 1);
	TEST_DEFINE_AND_SET(ac_datatype::int27, 1);
	TEST_DEFINE_AND_SET(ac_datatype::uint27, 1);
	TEST_DEFINE_AND_SET(ac_datatype::int28, 1);
	TEST_DEFINE_AND_SET(ac_datatype::uint28, 1);
	TEST_DEFINE_AND_SET(ac_datatype::int29, 1);
	TEST_DEFINE_AND_SET(ac_datatype::uint29, 1);
	TEST_DEFINE_AND_SET(ac_datatype::int30, 1);
	TEST_DEFINE_AND_SET(ac_datatype::uint30, 1);
	TEST_DEFINE_AND_SET(ac_datatype::int31, 1);
	TEST_DEFINE_AND_SET(ac_datatype::uint31, 1);
	TEST_DEFINE_AND_SET(ac_datatype::int32, 1);
	TEST_DEFINE_AND_SET(ac_datatype::uint32, 1);
	TEST_DEFINE_AND_SET(ac_datatype::int33, 1);
	TEST_DEFINE_AND_SET(ac_datatype::uint33, 1);
	TEST_DEFINE_AND_SET(ac_datatype::int34, 1);
	TEST_DEFINE_AND_SET(ac_datatype::uint34, 1);
	TEST_DEFINE_AND_SET(ac_datatype::int35, 1);
	TEST_DEFINE_AND_SET(ac_datatype::uint35, 1);
	TEST_DEFINE_AND_SET(ac_datatype::int36, 1);
	TEST_DEFINE_AND_SET(ac_datatype::uint36, 1);
	TEST_DEFINE_AND_SET(ac_datatype::int37, 1);
	TEST_DEFINE_AND_SET(ac_datatype::uint37, 1);
	TEST_DEFINE_AND_SET(ac_datatype::int38, 1);
	TEST_DEFINE_AND_SET(ac_datatype::uint38, 1);
	TEST_DEFINE_AND_SET(ac_datatype::int39, 1);
	TEST_DEFINE_AND_SET(ac_datatype::uint39, 1);
	TEST_DEFINE_AND_SET(ac_datatype::int40, 1);
	TEST_DEFINE_AND_SET(ac_datatype::uint40, 1);
	TEST_DEFINE_AND_SET(ac_datatype::int41, 1);
	TEST_DEFINE_AND_SET(ac_datatype::uint41, 1);
	TEST_DEFINE_AND_SET(ac_datatype::int42, 1);
	TEST_DEFINE_AND_SET(ac_datatype::uint42, 1);
	TEST_DEFINE_AND_SET(ac_datatype::int43, 1);
	TEST_DEFINE_AND_SET(ac_datatype::uint43, 1);
	TEST_DEFINE_AND_SET(ac_datatype::int44, 1);
	TEST_DEFINE_AND_SET(ac_datatype::uint44, 1);
	TEST_DEFINE_AND_SET(ac_datatype::int45, 1);
	TEST_DEFINE_AND_SET(ac_datatype::uint45, 1);
	TEST_DEFINE_AND_SET(ac_datatype::int46, 1);
	TEST_DEFINE_AND_SET(ac_datatype::uint46, 1);
	TEST_DEFINE_AND_SET(ac_datatype::int47, 1);
	TEST_DEFINE_AND_SET(ac_datatype::uint47, 1);
	TEST_DEFINE_AND_SET(ac_datatype::int48, 1);
	TEST_DEFINE_AND_SET(ac_datatype::uint48, 1);
	TEST_DEFINE_AND_SET(ac_datatype::int49, 1);
	TEST_DEFINE_AND_SET(ac_datatype::uint49, 1);
	TEST_DEFINE_AND_SET(ac_datatype::int50, 1);
	TEST_DEFINE_AND_SET(ac_datatype::uint50, 1);
	TEST_DEFINE_AND_SET(ac_datatype::int51, 1);
	TEST_DEFINE_AND_SET(ac_datatype::uint51, 1);
	TEST_DEFINE_AND_SET(ac_datatype::int52, 1);
	TEST_DEFINE_AND_SET(ac_datatype::uint52, 1);
	TEST_DEFINE_AND_SET(ac_datatype::int53, 1);
	TEST_DEFINE_AND_SET(ac_datatype::uint53, 1);
	TEST_DEFINE_AND_SET(ac_datatype::int54, 1);
	TEST_DEFINE_AND_SET(ac_datatype::uint54, 1);
	TEST_DEFINE_AND_SET(ac_datatype::int55, 1);
	TEST_DEFINE_AND_SET(ac_datatype::uint55, 1);
	TEST_DEFINE_AND_SET(ac_datatype::int56, 1);
	TEST_DEFINE_AND_SET(ac_datatype::uint56, 1);
	TEST_DEFINE_AND_SET(ac_datatype::int57, 1);
	TEST_DEFINE_AND_SET(ac_datatype::uint57, 1);
	TEST_DEFINE_AND_SET(ac_datatype::int58, 1);
	TEST_DEFINE_AND_SET(ac_datatype::uint58, 1);
	TEST_DEFINE_AND_SET(ac_datatype::int59, 1);
	TEST_DEFINE_AND_SET(ac_datatype::uint59, 1);
	TEST_DEFINE_AND_SET(ac_datatype::int60, 1);
	TEST_DEFINE_AND_SET(ac_datatype::uint60, 1);
	TEST_DEFINE_AND_SET(ac_datatype::int61, 1);
	TEST_DEFINE_AND_SET(ac_datatype::uint61, 1);
	TEST_DEFINE_AND_SET(ac_datatype::int62, 1);
	TEST_DEFINE_AND_SET(ac_datatype::uint62, 1);
	TEST_DEFINE_AND_SET(ac_datatype::int63, 1);
	TEST_DEFINE_AND_SET(ac_datatype::uint63, 1);


	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<1, 0, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<2, 0, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<3, 0, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<4, 0, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<5, 0, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<6, 0, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<7, 0, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<8, 0, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<9, 0, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<10, 0, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<11, 0, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<12, 0, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<13, 0, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<14, 0, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<15, 0, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<16, 0, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<17, 0, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<18, 0, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<19, 0, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<20, 0, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<21, 0, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<22, 0, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<23, 0, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<24, 0, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<25, 0, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<26, 0, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<27, 0, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<28, 0, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<29, 0, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<30, 0, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<31, 0, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<32, 0, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<33, 0, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<34, 0, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<35, 0, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<36, 0, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<37, 0, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<38, 0, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<39, 0, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<40, 0, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<41, 0, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<42, 0, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<43, 0, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<44, 0, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<45, 0, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<46, 0, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<47, 0, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<48, 0, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<49, 0, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<50, 0, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<51, 0, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<52, 0, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<53, 0, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<54, 0, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<55, 0, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<56, 0, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<57, 0, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<58, 0, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<59, 0, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<60, 0, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<61, 0, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<62, 0, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<63, 0, false>), 0.5);

	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<1, 1, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<2, 1, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<3, 1, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<4, 1, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<5, 1, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<6, 1, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<7, 1, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<8, 1, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<9, 1, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<10, 1, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<11, 1, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<12, 1, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<13, 1, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<14, 1, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<15, 1, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<16, 1, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<17, 1, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<18, 1, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<19, 1, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<20, 1, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<21, 1, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<22, 1, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<23, 1, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<24, 1, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<25, 1, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<26, 1, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<27, 1, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<28, 1, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<29, 1, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<30, 1, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<31, 1, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<32, 1, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<33, 1, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<34, 1, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<35, 1, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<36, 1, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<37, 1, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<38, 1, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<39, 1, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<40, 1, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<41, 1, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<42, 1, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<43, 1, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<44, 1, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<45, 1, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<46, 1, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<47, 1, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<48, 1, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<49, 1, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<50, 1, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<51, 1, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<52, 1, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<53, 1, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<54, 1, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<55, 1, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<56, 1, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<57, 1, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<58, 1, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<59, 1, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<60, 1, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<61, 1, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<62, 1, false>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<63, 1, false>), 0.5);



	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<1, 0, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<2, 0, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<3, 0, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<4, 0, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<5, 0, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<6, 0, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<7, 0, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<8, 0, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<9, 0, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<10, 0, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<11, 0, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<12, 0, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<13, 0, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<14, 0, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<15, 0, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<16, 0, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<17, 0, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<18, 0, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<19, 0, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<20, 0, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<21, 0, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<22, 0, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<23, 0, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<24, 0, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<25, 0, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<26, 0, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<27, 0, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<28, 0, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<29, 0, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<30, 0, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<31, 0, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<32, 0, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<33, 0, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<34, 0, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<35, 0, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<36, 0, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<37, 0, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<38, 0, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<39, 0, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<40, 0, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<41, 0, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<42, 0, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<43, 0, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<44, 0, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<45, 0, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<46, 0, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<47, 0, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<48, 0, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<49, 0, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<50, 0, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<51, 0, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<52, 0, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<53, 0, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<54, 0, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<55, 0, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<56, 0, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<57, 0, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<58, 0, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<59, 0, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<60, 0, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<61, 0, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<62, 0, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<63, 0, true>), 0.5);

	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<1, 1, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<2, 1, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<3, 1, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<4, 1, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<5, 1, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<6, 1, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<7, 1, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<8, 1, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<9, 1, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<10, 1, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<11, 1, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<12, 1, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<13, 1, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<14, 1, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<15, 1, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<16, 1, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<17, 1, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<18, 1, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<19, 1, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<20, 1, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<21, 1, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<22, 1, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<23, 1, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<24, 1, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<25, 1, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<26, 1, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<27, 1, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<28, 1, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<29, 1, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<30, 1, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<31, 1, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<32, 1, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<33, 1, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<34, 1, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<35, 1, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<36, 1, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<37, 1, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<38, 1, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<39, 1, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<40, 1, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<41, 1, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<42, 1, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<43, 1, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<44, 1, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<45, 1, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<46, 1, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<47, 1, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<48, 1, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<49, 1, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<50, 1, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<51, 1, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<52, 1, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<53, 1, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<54, 1, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<55, 1, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<56, 1, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<57, 1, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<58, 1, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<59, 1, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<60, 1, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<61, 1, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<62, 1, true>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_fixed<63, 1, true>), 0.5);

	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<1, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<2, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<3, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<4, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<5, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<6, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<7, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<8, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<9, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<10, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<11, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<12, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<13, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<14, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<15, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<16, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<17, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<18, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<19, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<20, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<21, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<22, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<23, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<24, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<25, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<26, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<27, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<28, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<29, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<30, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<31, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<32, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<33, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<34, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<35, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<36, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<37, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<38, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<39, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<40, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<41, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<42, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<43, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<44, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<45, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<46, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<47, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<48, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<49, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<50, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<51, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<52, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<53, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<54, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<55, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<56, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<57, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<58, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<59, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<60, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<61, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<62, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<63, 0, 8>), 0.5);

	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<1, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<2, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<3, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<4, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<5, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<6, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<7, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<8, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<9, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<10, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<11, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<12, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<13, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<14, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<15, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<16, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<17, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<18, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<19, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<20, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<21, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<22, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<23, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<24, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<25, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<26, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<27, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<28, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<29, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<30, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<31, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<32, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<33, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<34, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<35, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<36, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<37, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<38, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<39, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<40, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<41, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<42, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<43, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<44, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<45, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<46, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<47, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<48, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<49, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<50, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<51, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<52, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<53, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<54, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<55, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<56, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<57, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<58, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<59, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<60, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<61, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<62, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET(PACK(ac_datatype::ac_float<63, 1, 8>), 0.5);












	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::int1, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::uint1, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::int2, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::uint2, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::int3, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::uint3, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::int4, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::uint4, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::int5, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::uint5, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::int6, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::uint6, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::int7, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::uint7, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::int8, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::uint8, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::int9, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::uint9, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::int10, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::uint10, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::int11, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::uint11, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::int12, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::uint12, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::int13, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::uint13, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::int14, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::uint14, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::int15, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::uint15, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::int16, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::uint16, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::int17, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::uint17, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::int18, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::uint18, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::int19, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::uint19, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::int20, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::uint20, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::int21, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::uint21, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::int22, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::uint22, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::int23, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::uint23, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::int24, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::uint24, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::int25, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::uint25, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::int26, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::uint26, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::int27, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::uint27, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::int28, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::uint28, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::int29, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::uint29, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::int30, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::uint30, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::int31, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::uint31, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::int32, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::uint32, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::int33, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::uint33, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::int34, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::uint34, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::int35, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::uint35, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::int36, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::uint36, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::int37, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::uint37, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::int38, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::uint38, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::int39, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::uint39, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::int40, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::uint40, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::int41, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::uint41, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::int42, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::uint42, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::int43, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::uint43, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::int44, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::uint44, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::int45, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::uint45, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::int46, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::uint46, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::int47, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::uint47, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::int48, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::uint48, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::int49, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::uint49, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::int50, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::uint50, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::int51, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::uint51, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::int52, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::uint52, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::int53, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::uint53, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::int54, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::uint54, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::int55, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::uint55, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::int56, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::uint56, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::int57, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::uint57, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::int58, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::uint58, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::int59, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::uint59, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::int60, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::uint60, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::int61, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::uint61, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::int62, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::uint62, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::int63, 1);
	TEST_DEFINE_AND_SET_COMPLEX(ac_datatype::uint63, 1);


	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<1, 0, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<2, 0, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<3, 0, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<4, 0, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<5, 0, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<6, 0, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<7, 0, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<8, 0, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<9, 0, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<10, 0, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<11, 0, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<12, 0, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<13, 0, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<14, 0, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<15, 0, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<16, 0, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<17, 0, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<18, 0, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<19, 0, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<20, 0, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<21, 0, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<22, 0, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<23, 0, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<24, 0, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<25, 0, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<26, 0, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<27, 0, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<28, 0, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<29, 0, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<30, 0, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<31, 0, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<32, 0, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<33, 0, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<34, 0, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<35, 0, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<36, 0, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<37, 0, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<38, 0, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<39, 0, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<40, 0, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<41, 0, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<42, 0, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<43, 0, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<44, 0, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<45, 0, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<46, 0, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<47, 0, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<48, 0, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<49, 0, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<50, 0, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<51, 0, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<52, 0, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<53, 0, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<54, 0, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<55, 0, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<56, 0, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<57, 0, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<58, 0, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<59, 0, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<60, 0, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<61, 0, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<62, 0, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<63, 0, false>), 0.5);

	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<1, 1, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<2, 1, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<3, 1, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<4, 1, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<5, 1, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<6, 1, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<7, 1, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<8, 1, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<9, 1, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<10, 1, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<11, 1, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<12, 1, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<13, 1, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<14, 1, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<15, 1, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<16, 1, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<17, 1, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<18, 1, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<19, 1, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<20, 1, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<21, 1, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<22, 1, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<23, 1, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<24, 1, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<25, 1, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<26, 1, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<27, 1, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<28, 1, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<29, 1, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<30, 1, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<31, 1, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<32, 1, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<33, 1, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<34, 1, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<35, 1, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<36, 1, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<37, 1, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<38, 1, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<39, 1, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<40, 1, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<41, 1, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<42, 1, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<43, 1, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<44, 1, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<45, 1, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<46, 1, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<47, 1, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<48, 1, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<49, 1, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<50, 1, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<51, 1, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<52, 1, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<53, 1, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<54, 1, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<55, 1, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<56, 1, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<57, 1, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<58, 1, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<59, 1, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<60, 1, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<61, 1, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<62, 1, false>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<63, 1, false>), 0.5);



	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<1, 0, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<2, 0, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<3, 0, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<4, 0, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<5, 0, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<6, 0, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<7, 0, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<8, 0, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<9, 0, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<10, 0, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<11, 0, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<12, 0, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<13, 0, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<14, 0, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<15, 0, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<16, 0, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<17, 0, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<18, 0, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<19, 0, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<20, 0, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<21, 0, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<22, 0, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<23, 0, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<24, 0, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<25, 0, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<26, 0, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<27, 0, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<28, 0, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<29, 0, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<30, 0, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<31, 0, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<32, 0, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<33, 0, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<34, 0, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<35, 0, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<36, 0, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<37, 0, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<38, 0, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<39, 0, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<40, 0, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<41, 0, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<42, 0, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<43, 0, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<44, 0, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<45, 0, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<46, 0, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<47, 0, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<48, 0, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<49, 0, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<50, 0, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<51, 0, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<52, 0, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<53, 0, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<54, 0, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<55, 0, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<56, 0, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<57, 0, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<58, 0, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<59, 0, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<60, 0, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<61, 0, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<62, 0, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<63, 0, true>), 0.5);

	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<1, 1, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<2, 1, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<3, 1, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<4, 1, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<5, 1, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<6, 1, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<7, 1, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<8, 1, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<9, 1, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<10, 1, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<11, 1, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<12, 1, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<13, 1, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<14, 1, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<15, 1, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<16, 1, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<17, 1, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<18, 1, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<19, 1, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<20, 1, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<21, 1, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<22, 1, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<23, 1, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<24, 1, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<25, 1, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<26, 1, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<27, 1, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<28, 1, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<29, 1, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<30, 1, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<31, 1, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<32, 1, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<33, 1, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<34, 1, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<35, 1, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<36, 1, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<37, 1, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<38, 1, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<39, 1, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<40, 1, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<41, 1, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<42, 1, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<43, 1, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<44, 1, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<45, 1, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<46, 1, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<47, 1, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<48, 1, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<49, 1, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<50, 1, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<51, 1, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<52, 1, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<53, 1, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<54, 1, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<55, 1, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<56, 1, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<57, 1, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<58, 1, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<59, 1, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<60, 1, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<61, 1, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<62, 1, true>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_fixed<63, 1, true>), 0.5);

	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<1, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<2, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<3, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<4, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<5, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<6, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<7, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<8, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<9, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<10, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<11, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<12, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<13, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<14, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<15, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<16, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<17, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<18, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<19, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<20, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<21, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<22, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<23, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<24, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<25, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<26, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<27, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<28, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<29, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<30, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<31, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<32, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<33, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<34, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<35, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<36, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<37, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<38, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<39, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<40, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<41, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<42, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<43, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<44, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<45, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<46, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<47, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<48, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<49, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<50, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<51, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<52, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<53, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<54, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<55, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<56, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<57, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<58, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<59, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<60, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<61, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<62, 0, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<63, 0, 8>), 0.5);

	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<1, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<2, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<3, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<4, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<5, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<6, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<7, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<8, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<9, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<10, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<11, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<12, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<13, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<14, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<15, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<16, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<17, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<18, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<19, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<20, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<21, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<22, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<23, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<24, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<25, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<26, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<27, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<28, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<29, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<30, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<31, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<32, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<33, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<34, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<35, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<36, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<37, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<38, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<39, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<40, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<41, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<42, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<43, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<44, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<45, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<46, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<47, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<48, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<49, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<50, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<51, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<52, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<53, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<54, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<55, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<56, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<57, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<58, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<59, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<60, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<61, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<62, 1, 8>), 0.5);
	TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_datatype::ac_float<63, 1, 8>), 0.5);
}



int main()
{
	ac_datatype::ac_complex<ac_datatype::ac_fixed<16, 2>> a = 0.5;
	a.i() = 0.5;
	auto t = ac_datatype::ac_hex_string{ a };
	cout << t << endl;
	t = "0x01-02 03_04h";
	ac_datatype::ac_int<32, false> in1 = t;
	ac_datatype::ac_int<32, false> in2 = static_cast<ac_datatype::ac_int<32, false>>(t);

	cout << hex << static_cast<ac_datatype::ac_int<32, false>>(t) << endl << in2 << endl;

	{
		/*typedef Eigen::Matrix<ac_fixed<16, 1>, 4, 4> Matrix_f16;
		Matrix_f16 mat;
		mat << 0.1, 0.2, 0.3, 0.4, 0.1, 0.2, 0.3, 0.4, 0.1, 0.2, 0.3, 0.4, 0.1, 0.2, 0.3, 0.4;
		cout << mat << endl << mat * mat << endl;*/
	}


	{
		using namespace ac_datatype;

		auto t2 = "0110_0000b"_bin;
		ac_int<16, false> abbb = t2;
		cout << t2 << endl << ac_int<16, false>{t2} << endl;
		cout << t2 << endl << static_cast<ac_int<16, false>>(t2) << endl;
	}

	cout << ac_datatype::is_ac_basic_type<ac_datatype::uint16>::value << endl;
	cout << ac_datatype::is_ac_basic_type<uint16_t>::value << endl;
	cout << ac_datatype::is_ac_basic_type<ac_datatype::ac_fixed<32, 1>>::value << endl;
	cout << ac_datatype::is_ac_basic_type<ac_datatype::ac_float<32, 1, 8>>::value << endl;
	cout << ac_datatype::is_ac_basic_type<ac_datatype::ac_complex<ac_datatype::ac_fixed<32, 1>>>::value << endl;
	cout << ac_datatype::is_ac_basic_type<ac_datatype::ac_complex<ac_datatype::ac_float<32, 1, 8>>>::value << endl;



	test_defines();

	return 0;
}
