#include <iostream>
#include <sstream>
#include <ac_datatype_plus>

using namespace std;

#define PACK(...) __VA_ARGS__

#define TEST_DEFINE_AND_SET(TYPE,VALUE)\
    {\
        TYPE t = { VALUE };\
        cout << "define " # TYPE " and set to " << VALUE << " and got " << t << endl;\
    }

#define TEST_DEFINE_AND_SET_COMPLEX(TYPE,VALUE)\
    {\
        ac_complex<PACK(TYPE)> t = { VALUE };\
        cout << "define " # TYPE " and set to " << VALUE << " and got " << t << endl;\
    }


void test_defines()
{
    TEST_DEFINE_AND_SET(int1 , 1);
    TEST_DEFINE_AND_SET(uint1 , 1);
    TEST_DEFINE_AND_SET(int2 , 1);
    TEST_DEFINE_AND_SET(uint2 , 1);
    TEST_DEFINE_AND_SET(int3 , 1);
    TEST_DEFINE_AND_SET(uint3 , 1);
    TEST_DEFINE_AND_SET(int4 , 1);
    TEST_DEFINE_AND_SET(uint4 , 1);
    TEST_DEFINE_AND_SET(int5 , 1);
    TEST_DEFINE_AND_SET(uint5 , 1);
    TEST_DEFINE_AND_SET(int6 , 1);
    TEST_DEFINE_AND_SET(uint6 , 1);
    TEST_DEFINE_AND_SET(int7 , 1);
    TEST_DEFINE_AND_SET(uint7 , 1);
    TEST_DEFINE_AND_SET(int8 , 1);
    TEST_DEFINE_AND_SET(uint8 , 1);
    TEST_DEFINE_AND_SET(int9 , 1);
    TEST_DEFINE_AND_SET(uint9 , 1);
    TEST_DEFINE_AND_SET(int10 , 1);
    TEST_DEFINE_AND_SET(uint10, 1);
    TEST_DEFINE_AND_SET(int11 , 1);
    TEST_DEFINE_AND_SET(uint11, 1);
    TEST_DEFINE_AND_SET(int12 , 1);
    TEST_DEFINE_AND_SET(uint12, 1);
    TEST_DEFINE_AND_SET(int13 , 1);
    TEST_DEFINE_AND_SET(uint13, 1);
    TEST_DEFINE_AND_SET(int14 , 1);
    TEST_DEFINE_AND_SET(uint14, 1);
    TEST_DEFINE_AND_SET(int15 , 1);
    TEST_DEFINE_AND_SET(uint15, 1);
    TEST_DEFINE_AND_SET(int16 , 1);
    TEST_DEFINE_AND_SET(uint16, 1);
    TEST_DEFINE_AND_SET(int17 , 1);
    TEST_DEFINE_AND_SET(uint17, 1);
    TEST_DEFINE_AND_SET(int18 , 1);
    TEST_DEFINE_AND_SET(uint18, 1);
    TEST_DEFINE_AND_SET(int19 , 1);
    TEST_DEFINE_AND_SET(uint19, 1);
    TEST_DEFINE_AND_SET(int20 , 1);
    TEST_DEFINE_AND_SET(uint20, 1);
    TEST_DEFINE_AND_SET(int21 , 1);
    TEST_DEFINE_AND_SET(uint21, 1);
    TEST_DEFINE_AND_SET(int22 , 1);
    TEST_DEFINE_AND_SET(uint22, 1);
    TEST_DEFINE_AND_SET(int23 , 1);
    TEST_DEFINE_AND_SET(uint23, 1);
    TEST_DEFINE_AND_SET(int24 , 1);
    TEST_DEFINE_AND_SET(uint24, 1);
    TEST_DEFINE_AND_SET(int25 , 1);
    TEST_DEFINE_AND_SET(uint25, 1);
    TEST_DEFINE_AND_SET(int26 , 1);
    TEST_DEFINE_AND_SET(uint26, 1);
    TEST_DEFINE_AND_SET(int27 , 1);
    TEST_DEFINE_AND_SET(uint27, 1);
    TEST_DEFINE_AND_SET(int28 , 1);
    TEST_DEFINE_AND_SET(uint28, 1);
    TEST_DEFINE_AND_SET(int29 , 1);
    TEST_DEFINE_AND_SET(uint29, 1);
    TEST_DEFINE_AND_SET(int30 , 1);
    TEST_DEFINE_AND_SET(uint30, 1);
    TEST_DEFINE_AND_SET(int31 , 1);
    TEST_DEFINE_AND_SET(uint31, 1);
    TEST_DEFINE_AND_SET(int32 , 1);
    TEST_DEFINE_AND_SET(uint32, 1);
    TEST_DEFINE_AND_SET(int33 , 1);
    TEST_DEFINE_AND_SET(uint33, 1);
    TEST_DEFINE_AND_SET(int34 , 1);
    TEST_DEFINE_AND_SET(uint34, 1);
    TEST_DEFINE_AND_SET(int35 , 1);
    TEST_DEFINE_AND_SET(uint35, 1);
    TEST_DEFINE_AND_SET(int36 , 1);
    TEST_DEFINE_AND_SET(uint36, 1);
    TEST_DEFINE_AND_SET(int37 , 1);
    TEST_DEFINE_AND_SET(uint37, 1);
    TEST_DEFINE_AND_SET(int38 , 1);
    TEST_DEFINE_AND_SET(uint38, 1);
    TEST_DEFINE_AND_SET(int39 , 1);
    TEST_DEFINE_AND_SET(uint39, 1);
    TEST_DEFINE_AND_SET(int40 , 1);
    TEST_DEFINE_AND_SET(uint40, 1);
    TEST_DEFINE_AND_SET(int41 , 1);
    TEST_DEFINE_AND_SET(uint41, 1);
    TEST_DEFINE_AND_SET(int42 , 1);
    TEST_DEFINE_AND_SET(uint42, 1);
    TEST_DEFINE_AND_SET(int43 , 1);
    TEST_DEFINE_AND_SET(uint43, 1);
    TEST_DEFINE_AND_SET(int44 , 1);
    TEST_DEFINE_AND_SET(uint44, 1);
    TEST_DEFINE_AND_SET(int45 , 1);
    TEST_DEFINE_AND_SET(uint45, 1);
    TEST_DEFINE_AND_SET(int46 , 1);
    TEST_DEFINE_AND_SET(uint46, 1);
    TEST_DEFINE_AND_SET(int47 , 1);
    TEST_DEFINE_AND_SET(uint47, 1);
    TEST_DEFINE_AND_SET(int48 , 1);
    TEST_DEFINE_AND_SET(uint48, 1);
    TEST_DEFINE_AND_SET(int49 , 1);
    TEST_DEFINE_AND_SET(uint49, 1);
    TEST_DEFINE_AND_SET(int50 , 1);
    TEST_DEFINE_AND_SET(uint50, 1);
    TEST_DEFINE_AND_SET(int51 , 1);
    TEST_DEFINE_AND_SET(uint51, 1);
    TEST_DEFINE_AND_SET(int52 , 1);
    TEST_DEFINE_AND_SET(uint52, 1);
    TEST_DEFINE_AND_SET(int53 , 1);
    TEST_DEFINE_AND_SET(uint53, 1);
    TEST_DEFINE_AND_SET(int54 , 1);
    TEST_DEFINE_AND_SET(uint54, 1);
    TEST_DEFINE_AND_SET(int55 , 1);
    TEST_DEFINE_AND_SET(uint55, 1);
    TEST_DEFINE_AND_SET(int56 , 1);
    TEST_DEFINE_AND_SET(uint56, 1);
    TEST_DEFINE_AND_SET(int57 , 1);
    TEST_DEFINE_AND_SET(uint57, 1);
    TEST_DEFINE_AND_SET(int58 , 1);
    TEST_DEFINE_AND_SET(uint58, 1);
    TEST_DEFINE_AND_SET(int59 , 1);
    TEST_DEFINE_AND_SET(uint59, 1);
    TEST_DEFINE_AND_SET(int60 , 1);
    TEST_DEFINE_AND_SET(uint60, 1);
    TEST_DEFINE_AND_SET(int61 , 1);
    TEST_DEFINE_AND_SET(uint61, 1);
    TEST_DEFINE_AND_SET(int62 , 1);
    TEST_DEFINE_AND_SET(uint62, 1);
    TEST_DEFINE_AND_SET(int63 , 1);
    TEST_DEFINE_AND_SET(uint63, 1);


    TEST_DEFINE_AND_SET(PACK(ac_fixed<1 ,0, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<2 ,0, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<3 ,0, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<4 ,0, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<5 ,0, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<6 ,0, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<7 ,0, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<8 ,0, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<9 ,0, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<10 ,0, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<11 ,0, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<12 ,0, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<13 ,0, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<14 ,0, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<15 ,0, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<16 ,0, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<17 ,0, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<18 ,0, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<19 ,0, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<20, 0, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<21, 0, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<22, 0, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<23, 0, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<24, 0, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<25, 0, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<26, 0, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<27, 0, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<28, 0, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<29, 0, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<30, 0, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<31, 0, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<32, 0, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<33, 0, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<34, 0, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<35, 0, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<36, 0, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<37, 0, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<38, 0, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<39, 0, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<40, 0, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<41, 0, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<42, 0, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<43, 0, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<44, 0, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<45, 0, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<46, 0, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<47, 0, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<48, 0, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<49, 0, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<50, 0, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<51, 0, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<52, 0, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<53, 0, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<54, 0, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<55, 0, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<56, 0, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<57, 0, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<58, 0, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<59, 0, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<60, 0, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<61, 0, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<62, 0, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<63, 0, false>), 0.5);

    TEST_DEFINE_AND_SET(PACK(ac_fixed<1, 1, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<2, 1, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<3, 1, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<4, 1, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<5, 1, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<6, 1, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<7, 1, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<8, 1, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<9, 1, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<10, 1, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<11, 1, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<12, 1, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<13, 1, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<14, 1, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<15, 1, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<16, 1, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<17, 1, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<18, 1, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<19, 1, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<20, 1, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<21, 1, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<22, 1, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<23, 1, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<24, 1, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<25, 1, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<26, 1, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<27, 1, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<28, 1, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<29, 1, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<30, 1, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<31, 1, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<32, 1, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<33, 1, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<34, 1, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<35, 1, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<36, 1, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<37, 1, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<38, 1, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<39, 1, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<40, 1, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<41, 1, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<42, 1, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<43, 1, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<44, 1, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<45, 1, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<46, 1, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<47, 1, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<48, 1, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<49, 1, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<50, 1, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<51, 1, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<52, 1, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<53, 1, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<54, 1, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<55, 1, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<56, 1, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<57, 1, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<58, 1, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<59, 1, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<60, 1, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<61, 1, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<62, 1, false>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<63, 1, false>), 0.5);



    TEST_DEFINE_AND_SET(PACK(ac_fixed<1, 0, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<2, 0, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<3, 0, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<4, 0, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<5, 0, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<6, 0, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<7, 0, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<8, 0, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<9, 0, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<10, 0, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<11, 0, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<12, 0, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<13, 0, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<14, 0, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<15, 0, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<16, 0, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<17, 0, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<18, 0, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<19, 0, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<20, 0, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<21, 0, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<22, 0, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<23, 0, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<24, 0, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<25, 0, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<26, 0, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<27, 0, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<28, 0, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<29, 0, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<30, 0, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<31, 0, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<32, 0, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<33, 0, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<34, 0, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<35, 0, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<36, 0, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<37, 0, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<38, 0, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<39, 0, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<40, 0, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<41, 0, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<42, 0, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<43, 0, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<44, 0, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<45, 0, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<46, 0, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<47, 0, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<48, 0, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<49, 0, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<50, 0, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<51, 0, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<52, 0, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<53, 0, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<54, 0, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<55, 0, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<56, 0, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<57, 0, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<58, 0, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<59, 0, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<60, 0, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<61, 0, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<62, 0, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<63, 0, true>), 0.5);

    TEST_DEFINE_AND_SET(PACK(ac_fixed<1, 1, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<2, 1, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<3, 1, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<4, 1, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<5, 1, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<6, 1, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<7, 1, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<8, 1, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<9, 1, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<10, 1, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<11, 1, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<12, 1, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<13, 1, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<14, 1, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<15, 1, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<16, 1, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<17, 1, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<18, 1, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<19, 1, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<20, 1, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<21, 1, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<22, 1, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<23, 1, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<24, 1, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<25, 1, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<26, 1, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<27, 1, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<28, 1, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<29, 1, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<30, 1, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<31, 1, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<32, 1, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<33, 1, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<34, 1, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<35, 1, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<36, 1, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<37, 1, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<38, 1, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<39, 1, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<40, 1, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<41, 1, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<42, 1, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<43, 1, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<44, 1, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<45, 1, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<46, 1, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<47, 1, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<48, 1, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<49, 1, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<50, 1, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<51, 1, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<52, 1, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<53, 1, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<54, 1, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<55, 1, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<56, 1, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<57, 1, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<58, 1, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<59, 1, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<60, 1, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<61, 1, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<62, 1, true>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_fixed<63, 1, true>), 0.5);

    TEST_DEFINE_AND_SET(PACK(ac_float<1, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<2, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<3, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<4, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<5, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<6, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<7, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<8, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<9, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<10, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<11, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<12, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<13, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<14, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<15, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<16, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<17, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<18, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<19, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<20, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<21, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<22, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<23, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<24, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<25, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<26, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<27, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<28, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<29, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<30, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<31, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<32, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<33, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<34, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<35, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<36, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<37, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<38, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<39, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<40, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<41, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<42, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<43, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<44, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<45, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<46, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<47, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<48, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<49, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<50, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<51, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<52, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<53, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<54, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<55, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<56, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<57, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<58, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<59, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<60, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<61, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<62, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<63, 0, 8>), 0.5);

    TEST_DEFINE_AND_SET(PACK(ac_float<1, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<2, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<3, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<4, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<5, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<6, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<7, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<8, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<9, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<10, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<11, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<12, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<13, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<14, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<15, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<16, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<17, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<18, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<19, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<20, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<21, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<22, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<23, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<24, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<25, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<26, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<27, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<28, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<29, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<30, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<31, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<32, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<33, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<34, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<35, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<36, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<37, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<38, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<39, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<40, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<41, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<42, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<43, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<44, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<45, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<46, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<47, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<48, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<49, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<50, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<51, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<52, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<53, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<54, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<55, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<56, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<57, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<58, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<59, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<60, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<61, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<62, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET(PACK(ac_float<63, 1, 8>), 0.5);












    TEST_DEFINE_AND_SET_COMPLEX(int1, 1);
    TEST_DEFINE_AND_SET_COMPLEX(uint1, 1);
    TEST_DEFINE_AND_SET_COMPLEX(int2, 1);
    TEST_DEFINE_AND_SET_COMPLEX(uint2, 1);
    TEST_DEFINE_AND_SET_COMPLEX(int3, 1);
    TEST_DEFINE_AND_SET_COMPLEX(uint3, 1);
    TEST_DEFINE_AND_SET_COMPLEX(int4, 1);
    TEST_DEFINE_AND_SET_COMPLEX(uint4, 1);
    TEST_DEFINE_AND_SET_COMPLEX(int5, 1);
    TEST_DEFINE_AND_SET_COMPLEX(uint5, 1);
    TEST_DEFINE_AND_SET_COMPLEX(int6, 1);
    TEST_DEFINE_AND_SET_COMPLEX(uint6, 1);
    TEST_DEFINE_AND_SET_COMPLEX(int7, 1);
    TEST_DEFINE_AND_SET_COMPLEX(uint7, 1);
    TEST_DEFINE_AND_SET_COMPLEX(int8, 1);
    TEST_DEFINE_AND_SET_COMPLEX(uint8, 1);
    TEST_DEFINE_AND_SET_COMPLEX(int9, 1);
    TEST_DEFINE_AND_SET_COMPLEX(uint9, 1);
    TEST_DEFINE_AND_SET_COMPLEX(int10, 1);
    TEST_DEFINE_AND_SET_COMPLEX(uint10, 1);
    TEST_DEFINE_AND_SET_COMPLEX(int11, 1);
    TEST_DEFINE_AND_SET_COMPLEX(uint11, 1);
    TEST_DEFINE_AND_SET_COMPLEX(int12, 1);
    TEST_DEFINE_AND_SET_COMPLEX(uint12, 1);
    TEST_DEFINE_AND_SET_COMPLEX(int13, 1);
    TEST_DEFINE_AND_SET_COMPLEX(uint13, 1);
    TEST_DEFINE_AND_SET_COMPLEX(int14, 1);
    TEST_DEFINE_AND_SET_COMPLEX(uint14, 1);
    TEST_DEFINE_AND_SET_COMPLEX(int15, 1);
    TEST_DEFINE_AND_SET_COMPLEX(uint15, 1);
    TEST_DEFINE_AND_SET_COMPLEX(int16, 1);
    TEST_DEFINE_AND_SET_COMPLEX(uint16, 1);
    TEST_DEFINE_AND_SET_COMPLEX(int17, 1);
    TEST_DEFINE_AND_SET_COMPLEX(uint17, 1);
    TEST_DEFINE_AND_SET_COMPLEX(int18, 1);
    TEST_DEFINE_AND_SET_COMPLEX(uint18, 1);
    TEST_DEFINE_AND_SET_COMPLEX(int19, 1);
    TEST_DEFINE_AND_SET_COMPLEX(uint19, 1);
    TEST_DEFINE_AND_SET_COMPLEX(int20, 1);
    TEST_DEFINE_AND_SET_COMPLEX(uint20, 1);
    TEST_DEFINE_AND_SET_COMPLEX(int21, 1);
    TEST_DEFINE_AND_SET_COMPLEX(uint21, 1);
    TEST_DEFINE_AND_SET_COMPLEX(int22, 1);
    TEST_DEFINE_AND_SET_COMPLEX(uint22, 1);
    TEST_DEFINE_AND_SET_COMPLEX(int23, 1);
    TEST_DEFINE_AND_SET_COMPLEX(uint23, 1);
    TEST_DEFINE_AND_SET_COMPLEX(int24, 1);
    TEST_DEFINE_AND_SET_COMPLEX(uint24, 1);
    TEST_DEFINE_AND_SET_COMPLEX(int25, 1);
    TEST_DEFINE_AND_SET_COMPLEX(uint25, 1);
    TEST_DEFINE_AND_SET_COMPLEX(int26, 1);
    TEST_DEFINE_AND_SET_COMPLEX(uint26, 1);
    TEST_DEFINE_AND_SET_COMPLEX(int27, 1);
    TEST_DEFINE_AND_SET_COMPLEX(uint27, 1);
    TEST_DEFINE_AND_SET_COMPLEX(int28, 1);
    TEST_DEFINE_AND_SET_COMPLEX(uint28, 1);
    TEST_DEFINE_AND_SET_COMPLEX(int29, 1);
    TEST_DEFINE_AND_SET_COMPLEX(uint29, 1);
    TEST_DEFINE_AND_SET_COMPLEX(int30, 1);
    TEST_DEFINE_AND_SET_COMPLEX(uint30, 1);
    TEST_DEFINE_AND_SET_COMPLEX(int31, 1);
    TEST_DEFINE_AND_SET_COMPLEX(uint31, 1);
    TEST_DEFINE_AND_SET_COMPLEX(int32, 1);
    TEST_DEFINE_AND_SET_COMPLEX(uint32, 1);
    TEST_DEFINE_AND_SET_COMPLEX(int33, 1);
    TEST_DEFINE_AND_SET_COMPLEX(uint33, 1);
    TEST_DEFINE_AND_SET_COMPLEX(int34, 1);
    TEST_DEFINE_AND_SET_COMPLEX(uint34, 1);
    TEST_DEFINE_AND_SET_COMPLEX(int35, 1);
    TEST_DEFINE_AND_SET_COMPLEX(uint35, 1);
    TEST_DEFINE_AND_SET_COMPLEX(int36, 1);
    TEST_DEFINE_AND_SET_COMPLEX(uint36, 1);
    TEST_DEFINE_AND_SET_COMPLEX(int37, 1);
    TEST_DEFINE_AND_SET_COMPLEX(uint37, 1);
    TEST_DEFINE_AND_SET_COMPLEX(int38, 1);
    TEST_DEFINE_AND_SET_COMPLEX(uint38, 1);
    TEST_DEFINE_AND_SET_COMPLEX(int39, 1);
    TEST_DEFINE_AND_SET_COMPLEX(uint39, 1);
    TEST_DEFINE_AND_SET_COMPLEX(int40, 1);
    TEST_DEFINE_AND_SET_COMPLEX(uint40, 1);
    TEST_DEFINE_AND_SET_COMPLEX(int41, 1);
    TEST_DEFINE_AND_SET_COMPLEX(uint41, 1);
    TEST_DEFINE_AND_SET_COMPLEX(int42, 1);
    TEST_DEFINE_AND_SET_COMPLEX(uint42, 1);
    TEST_DEFINE_AND_SET_COMPLEX(int43, 1);
    TEST_DEFINE_AND_SET_COMPLEX(uint43, 1);
    TEST_DEFINE_AND_SET_COMPLEX(int44, 1);
    TEST_DEFINE_AND_SET_COMPLEX(uint44, 1);
    TEST_DEFINE_AND_SET_COMPLEX(int45, 1);
    TEST_DEFINE_AND_SET_COMPLEX(uint45, 1);
    TEST_DEFINE_AND_SET_COMPLEX(int46, 1);
    TEST_DEFINE_AND_SET_COMPLEX(uint46, 1);
    TEST_DEFINE_AND_SET_COMPLEX(int47, 1);
    TEST_DEFINE_AND_SET_COMPLEX(uint47, 1);
    TEST_DEFINE_AND_SET_COMPLEX(int48, 1);
    TEST_DEFINE_AND_SET_COMPLEX(uint48, 1);
    TEST_DEFINE_AND_SET_COMPLEX(int49, 1);
    TEST_DEFINE_AND_SET_COMPLEX(uint49, 1);
    TEST_DEFINE_AND_SET_COMPLEX(int50, 1);
    TEST_DEFINE_AND_SET_COMPLEX(uint50, 1);
    TEST_DEFINE_AND_SET_COMPLEX(int51, 1);
    TEST_DEFINE_AND_SET_COMPLEX(uint51, 1);
    TEST_DEFINE_AND_SET_COMPLEX(int52, 1);
    TEST_DEFINE_AND_SET_COMPLEX(uint52, 1);
    TEST_DEFINE_AND_SET_COMPLEX(int53, 1);
    TEST_DEFINE_AND_SET_COMPLEX(uint53, 1);
    TEST_DEFINE_AND_SET_COMPLEX(int54, 1);
    TEST_DEFINE_AND_SET_COMPLEX(uint54, 1);
    TEST_DEFINE_AND_SET_COMPLEX(int55, 1);
    TEST_DEFINE_AND_SET_COMPLEX(uint55, 1);
    TEST_DEFINE_AND_SET_COMPLEX(int56, 1);
    TEST_DEFINE_AND_SET_COMPLEX(uint56, 1);
    TEST_DEFINE_AND_SET_COMPLEX(int57, 1);
    TEST_DEFINE_AND_SET_COMPLEX(uint57, 1);
    TEST_DEFINE_AND_SET_COMPLEX(int58, 1);
    TEST_DEFINE_AND_SET_COMPLEX(uint58, 1);
    TEST_DEFINE_AND_SET_COMPLEX(int59, 1);
    TEST_DEFINE_AND_SET_COMPLEX(uint59, 1);
    TEST_DEFINE_AND_SET_COMPLEX(int60, 1);
    TEST_DEFINE_AND_SET_COMPLEX(uint60, 1);
    TEST_DEFINE_AND_SET_COMPLEX(int61, 1);
    TEST_DEFINE_AND_SET_COMPLEX(uint61, 1);
    TEST_DEFINE_AND_SET_COMPLEX(int62, 1);
    TEST_DEFINE_AND_SET_COMPLEX(uint62, 1);
    TEST_DEFINE_AND_SET_COMPLEX(int63, 1);
    TEST_DEFINE_AND_SET_COMPLEX(uint63, 1);


    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<1, 0, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<2, 0, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<3, 0, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<4, 0, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<5, 0, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<6, 0, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<7, 0, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<8, 0, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<9, 0, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<10, 0, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<11, 0, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<12, 0, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<13, 0, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<14, 0, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<15, 0, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<16, 0, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<17, 0, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<18, 0, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<19, 0, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<20, 0, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<21, 0, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<22, 0, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<23, 0, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<24, 0, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<25, 0, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<26, 0, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<27, 0, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<28, 0, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<29, 0, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<30, 0, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<31, 0, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<32, 0, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<33, 0, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<34, 0, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<35, 0, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<36, 0, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<37, 0, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<38, 0, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<39, 0, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<40, 0, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<41, 0, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<42, 0, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<43, 0, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<44, 0, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<45, 0, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<46, 0, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<47, 0, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<48, 0, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<49, 0, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<50, 0, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<51, 0, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<52, 0, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<53, 0, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<54, 0, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<55, 0, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<56, 0, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<57, 0, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<58, 0, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<59, 0, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<60, 0, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<61, 0, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<62, 0, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<63, 0, false>), 0.5);

    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<1, 1, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<2, 1, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<3, 1, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<4, 1, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<5, 1, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<6, 1, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<7, 1, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<8, 1, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<9, 1, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<10, 1, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<11, 1, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<12, 1, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<13, 1, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<14, 1, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<15, 1, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<16, 1, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<17, 1, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<18, 1, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<19, 1, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<20, 1, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<21, 1, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<22, 1, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<23, 1, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<24, 1, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<25, 1, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<26, 1, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<27, 1, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<28, 1, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<29, 1, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<30, 1, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<31, 1, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<32, 1, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<33, 1, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<34, 1, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<35, 1, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<36, 1, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<37, 1, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<38, 1, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<39, 1, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<40, 1, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<41, 1, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<42, 1, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<43, 1, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<44, 1, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<45, 1, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<46, 1, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<47, 1, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<48, 1, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<49, 1, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<50, 1, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<51, 1, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<52, 1, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<53, 1, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<54, 1, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<55, 1, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<56, 1, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<57, 1, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<58, 1, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<59, 1, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<60, 1, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<61, 1, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<62, 1, false>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<63, 1, false>), 0.5);



    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<1, 0, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<2, 0, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<3, 0, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<4, 0, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<5, 0, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<6, 0, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<7, 0, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<8, 0, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<9, 0, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<10, 0, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<11, 0, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<12, 0, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<13, 0, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<14, 0, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<15, 0, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<16, 0, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<17, 0, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<18, 0, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<19, 0, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<20, 0, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<21, 0, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<22, 0, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<23, 0, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<24, 0, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<25, 0, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<26, 0, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<27, 0, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<28, 0, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<29, 0, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<30, 0, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<31, 0, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<32, 0, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<33, 0, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<34, 0, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<35, 0, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<36, 0, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<37, 0, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<38, 0, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<39, 0, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<40, 0, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<41, 0, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<42, 0, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<43, 0, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<44, 0, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<45, 0, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<46, 0, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<47, 0, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<48, 0, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<49, 0, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<50, 0, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<51, 0, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<52, 0, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<53, 0, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<54, 0, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<55, 0, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<56, 0, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<57, 0, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<58, 0, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<59, 0, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<60, 0, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<61, 0, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<62, 0, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<63, 0, true>), 0.5);

    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<1, 1, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<2, 1, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<3, 1, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<4, 1, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<5, 1, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<6, 1, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<7, 1, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<8, 1, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<9, 1, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<10, 1, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<11, 1, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<12, 1, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<13, 1, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<14, 1, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<15, 1, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<16, 1, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<17, 1, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<18, 1, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<19, 1, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<20, 1, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<21, 1, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<22, 1, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<23, 1, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<24, 1, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<25, 1, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<26, 1, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<27, 1, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<28, 1, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<29, 1, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<30, 1, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<31, 1, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<32, 1, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<33, 1, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<34, 1, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<35, 1, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<36, 1, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<37, 1, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<38, 1, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<39, 1, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<40, 1, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<41, 1, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<42, 1, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<43, 1, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<44, 1, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<45, 1, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<46, 1, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<47, 1, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<48, 1, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<49, 1, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<50, 1, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<51, 1, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<52, 1, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<53, 1, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<54, 1, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<55, 1, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<56, 1, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<57, 1, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<58, 1, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<59, 1, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<60, 1, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<61, 1, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<62, 1, true>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_fixed<63, 1, true>), 0.5);

    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<1, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<2, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<3, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<4, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<5, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<6, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<7, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<8, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<9, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<10, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<11, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<12, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<13, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<14, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<15, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<16, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<17, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<18, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<19, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<20, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<21, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<22, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<23, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<24, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<25, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<26, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<27, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<28, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<29, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<30, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<31, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<32, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<33, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<34, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<35, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<36, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<37, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<38, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<39, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<40, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<41, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<42, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<43, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<44, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<45, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<46, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<47, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<48, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<49, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<50, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<51, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<52, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<53, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<54, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<55, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<56, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<57, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<58, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<59, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<60, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<61, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<62, 0, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<63, 0, 8>), 0.5);

    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<1, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<2, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<3, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<4, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<5, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<6, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<7, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<8, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<9, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<10, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<11, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<12, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<13, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<14, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<15, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<16, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<17, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<18, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<19, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<20, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<21, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<22, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<23, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<24, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<25, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<26, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<27, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<28, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<29, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<30, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<31, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<32, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<33, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<34, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<35, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<36, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<37, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<38, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<39, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<40, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<41, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<42, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<43, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<44, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<45, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<46, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<47, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<48, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<49, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<50, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<51, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<52, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<53, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<54, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<55, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<56, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<57, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<58, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<59, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<60, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<61, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<62, 1, 8>), 0.5);
    TEST_DEFINE_AND_SET_COMPLEX(PACK(ac_float<63, 1, 8>), 0.5);
}

int main()
{
    ac_complex<ac_fixed<16, 2>> a = 0.5;
    a.i() = 0.5;
    auto t = ac_hex_string{ a };
    cout << t << endl;
    cout << static_cast<ac_int<32, false>>(t) << endl;

    test_defines();

    return 0;
}
